export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const SAVE_EXHIB_ART_BEGIN = 'SAVE_EXHIB_ART_BEGIN'
export const SAVE_EXHIB_ART_SUCCESS = 'SAVE_EXHIB_ART_SUCCESS'
export const SAVE_EXHIB_ART_ERROR = 'SAVE_EXHIB_ART_ERROR'

export const SAVE_COLLEC_ART_BEGIN = 'SAVE_COLLEC_ART_BEGIN'
export const SAVE_COLLEC_ART_SUCCESS = 'SAVE_COLLEC_ART_SUCCESS'
export const SAVE_COLLEC_ART_ERROR = 'SAVE_COLLEC_ART_ERROR'

export const GET_USER_ART_BEGIN = 'GET_USER_ART_BEGIN'
export const GET_USER_ART_SUCCESS = 'GET_USER_ART_SUCCESS'

export const GET_USER_COLLEC_ART_BEGIN = 'GET_USER_COLLEC_ART_BEGIN'
export const GET_USER_COLLEC_ART_SUCCESS = 'GET_USER_COLLEC_ART_SUCCESS'

export const DELETE_EXHIB_ART_BEGIN = 'DELETE_EXHIB_ART_BEGIN'
export const DELETE_COLLEC_ART_BEGIN = 'DELETE_COLLEC_ART_BEGIN'

export const EDIT_ART_BEGIN = 'EDIT_ART_BEGIN'
export const EDIT_ART_SUCCESS = 'EDIT_ART_SUCCESS'
export const EDIT_ART_ERROR = 'EDIT_ART_ERROR'

export const EDIT_COLLEC_ART_BEGIN = 'EDIT_COLLEC_ART_BEGIN'
export const EDIT_COLLEC_ART_SUCCESS = 'EDIT_COLLEC_ART_SUCCESS'
export const EDIT_COLLEC_ART_ERROR = 'EDIT_COLLEC_ART_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_PAGE_COLLEC = 'CHANGE_PAGE_COLLEC'
